# This file was generated by GoReleaser. DO NOT EDIT.
cask "dotctl" do
  version "1.14.2"

  on_macos do
    on_intel do
      sha256 "e1ad161c2061507c6acfc7d98a53a2e49519c98927776e0d794fb3a483e0f008"
      url "https://github.com/felipe-veas/dotctl/releases/download/v#{version}/dotctl_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4f4a0fba3d712bb15ba0da9d4a28565dd1c4b03367d360820e55c54cd510d333"
      url "https://github.com/felipe-veas/dotctl/releases/download/v#{version}/dotctl_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1c383bea128c2162f676538b976e80e819c7c4b25b40be4369e565ef919a2924"
      url "https://github.com/felipe-veas/dotctl/releases/download/v#{version}/dotctl_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "07864b616af8934bfed12c46faea80ce3dcf6a2683551d25c33ed933aaf2c425"
      url "https://github.com/felipe-veas/dotctl/releases/download/v#{version}/dotctl_Linux_arm64.tar.gz"
    end
  end

  name "dotctl"
  desc "Sync dotfiles across machines (macOS + Linux)"
  homepage "https://github.com/felipe-veas/dotctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dotctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: [
          "-dr",
          "com.apple.quarantine",
          "#{staged_path}/dotctl",
        ]
    end
  end

  # No zap stanza required

end
