# This file was generated by GoReleaser. DO NOT EDIT.
cask "dotctl" do
  version "1.14.3"

  on_macos do
    on_intel do
      sha256 "5a7a6dcb97c6c99222544ea0676947a99fec01a894d5c6521b45c7b0a0dd56dd"
      url "https://github.com/felipe-veas/dotctl/releases/download/v#{version}/dotctl_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6f168e10ab20da0955f8eaa337cd3dde08f7c178bf9bdf42d9b0099af1680ad3"
      url "https://github.com/felipe-veas/dotctl/releases/download/v#{version}/dotctl_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a3919892d1e19f45b1f01f6f695668cd02e2525cc66c6dae40de13e4717d19f0"
      url "https://github.com/felipe-veas/dotctl/releases/download/v#{version}/dotctl_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "235f540299bcfc32f2dad3b738e0925aae502aaf5f3f4e8cb624487884ada0b5"
      url "https://github.com/felipe-veas/dotctl/releases/download/v#{version}/dotctl_Linux_arm64.tar.gz"
    end
  end

  name "dotctl"
  desc "Sync dotfiles across machines (macOS + Linux)"
  homepage "https://github.com/felipe-veas/dotctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dotctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: [
          "-dr",
          "com.apple.quarantine",
          "#{staged_path}/dotctl",
        ]
    end
  end

  # No zap stanza required

end
