# This file was generated by GoReleaser. DO NOT EDIT.
cask "dotctl" do
  version "1.14.0"

  on_macos do
    on_intel do
      sha256 "fbc90735eaf6b5069ed171e77804533e0c9f555fd4813d53d1bd2180454f988c"
      url "https://github.com/felipe-veas/dotctl/releases/download/v#{version}/dotctl_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ded7dcf1763a91bcd736ab45b01d4a4d5f23dd69c642bcccd3c27ef5a600faf4"
      url "https://github.com/felipe-veas/dotctl/releases/download/v#{version}/dotctl_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "061dc015482958b47e3ce71c6d41ae220e9a2803781f250c5e24153e47547c4c"
      url "https://github.com/felipe-veas/dotctl/releases/download/v#{version}/dotctl_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2dabd55b2442e88fd4f7b0d00fab102a010c89e7df92ddb3bd92f9da0a77243c"
      url "https://github.com/felipe-veas/dotctl/releases/download/v#{version}/dotctl_Linux_arm64.tar.gz"
    end
  end

  name "dotctl"
  desc "Sync dotfiles across machines (macOS + Linux)"
  homepage "https://github.com/felipe-veas/dotctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dotctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: [
          "-dr",
          "com.apple.quarantine",
          "#{staged_path}/dotctl",
        ]
    end
  end

  # No zap stanza required

end
