# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotctl < Formula
  desc "Sync dotfiles across machines (macOS + Linux)"
  homepage "https://github.com/felipe-veas/dotctl"
  version "1.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felipe-veas/dotctl/releases/download/v1.5.0/dotctl_Darwin_x86_64.tar.gz"
      sha256 "d81f665664c2e70418b92e1636f9a728c5a431f7d07e81ee791a294c28f5763f"

      def install
        bin.install "dotctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felipe-veas/dotctl/releases/download/v1.5.0/dotctl_Darwin_arm64.tar.gz"
      sha256 "d1135610e66bf8408d2564c901976bbe7c634343093beddfd3dc66c1711ec939"

      def install
        bin.install "dotctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felipe-veas/dotctl/releases/download/v1.5.0/dotctl_Linux_x86_64.tar.gz"
      sha256 "506d6a823de27349b76c31648985cdfd3b91f0bc2ad635a088a07e5d32cdc370"
      def install
        bin.install "dotctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felipe-veas/dotctl/releases/download/v1.5.0/dotctl_Linux_arm64.tar.gz"
      sha256 "da75d187fcac35e54f95d8de4622847dfad312e1c69e361de0f6c9209cccf716"
      def install
        bin.install "dotctl"
      end
    end
  end

  test do
    system "#{bin}/dotctl version"
  end
end
