# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotctl < Formula
  desc "Sync dotfiles across machines (macOS + Linux)"
  homepage "https://github.com/felipe-veas/dotctl"
  version "1.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felipe-veas/dotctl/releases/download/v1.8.0/dotctl_Darwin_x86_64.tar.gz"
      sha256 "4f15d39932eaf28a7f8cc6d1c7d9eb695137da8999346f440cadfa9ddbef4a85"

      def install
        bin.install "dotctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felipe-veas/dotctl/releases/download/v1.8.0/dotctl_Darwin_arm64.tar.gz"
      sha256 "f5095a3dbf461a6631bee7e33dd435de29a112142ab86718cf82d534e5e7f042"

      def install
        bin.install "dotctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felipe-veas/dotctl/releases/download/v1.8.0/dotctl_Linux_x86_64.tar.gz"
      sha256 "30944f5bfad3eda0291525e63e88d27944ec25fa75ce7471898893c5865350cd"
      def install
        bin.install "dotctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felipe-veas/dotctl/releases/download/v1.8.0/dotctl_Linux_arm64.tar.gz"
      sha256 "bc8db3075956f36a0a0a995c440ba93e0ff2f225d06b5a776e95b0d080c1495b"
      def install
        bin.install "dotctl"
      end
    end
  end

  test do
    system "#{bin}/dotctl version"
  end
end
