# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotctl < Formula
  desc "Sync dotfiles across machines (macOS + Linux)"
  homepage "https://github.com/felipe-veas/dotctl"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felipe-veas/dotctl/releases/download/v1.2.0/dotctl_Darwin_x86_64.tar.gz"
      sha256 "de2a0d739e1e4872336fea769a398be4e4cbeba3e902b7981fd0b9e382216ba9"

      def install
        bin.install "dotctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felipe-veas/dotctl/releases/download/v1.2.0/dotctl_Darwin_arm64.tar.gz"
      sha256 "5f5e8654200cca78f136653f0896a6d4132368dd95e398a9dfa6066a278095a9"

      def install
        bin.install "dotctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felipe-veas/dotctl/releases/download/v1.2.0/dotctl_Linux_x86_64.tar.gz"
      sha256 "e84b3a72decea6bc09b4537a4e549eefd21679c0b8f11fdcaee36f814e571f47"
      def install
        bin.install "dotctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felipe-veas/dotctl/releases/download/v1.2.0/dotctl_Linux_arm64.tar.gz"
      sha256 "fee135f32a2f264274b0e5cdc5dfb823948fb0a963000702472ae3fb2e26a5d6"
      def install
        bin.install "dotctl"
      end
    end
  end

  test do
    system "#{bin}/dotctl version"
  end
end
