# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kpdbug < Formula
  desc "Kubernetes pod debugging tool"
  homepage "https://github.com/felipe-veas/k8s-pods-debug"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felipe-veas/k8s-pods-debug/releases/download/v0.1.0/kpdbug_Darwin_x86_64.tar.gz"
      sha256 "8b2e61e795cc840169a60250dd893d0dba456711795c6fb4622741617f047345"

      def install
        bin.install "kpdbug"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felipe-veas/k8s-pods-debug/releases/download/v0.1.0/kpdbug_Darwin_arm64.tar.gz"
      sha256 "653e27eebe76449bb9db5b858fb9654d1d9bce8dea56a83f2835e08fa14c57ba"

      def install
        bin.install "kpdbug"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felipe-veas/k8s-pods-debug/releases/download/v0.1.0/kpdbug_Linux_x86_64.tar.gz"
      sha256 "9efcc74bd4e711ef4681535c377f57d4fbe9421b7ac2568c72100b4c16f0044e"
      def install
        bin.install "kpdbug"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felipe-veas/k8s-pods-debug/releases/download/v0.1.0/kpdbug_Linux_arm64.tar.gz"
      sha256 "a5a00ec3e7f60ad5db832e83824dbad23df466e69a6369bc2dfa6e006dcf1a71"
      def install
        bin.install "kpdbug"
      end
    end
  end

  test do
    system "#{bin}/kpdbug --version"
  end
end
