# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kpdbug < Formula
  desc "Kubernetes pod debugging tool"
  homepage "https://github.com/felipe-veas/k8s-pods-debug"
  version "1.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felipe-veas/k8s-pods-debug-releases/releases/download/v1.4.1/kpdbug_Darwin_x86_64.tar.gz"
      sha256 "8b688e3c532d0569b5fe75ca32197ec2df82558930746df67484a2f513ce01b7"

      def install
        bin.install "kpdbug"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felipe-veas/k8s-pods-debug-releases/releases/download/v1.4.1/kpdbug_Darwin_arm64.tar.gz"
      sha256 "59f26247595d68a5ae8d49419b832a904996e7dd4f1e42948b67e6474d7a4a9b"

      def install
        bin.install "kpdbug"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felipe-veas/k8s-pods-debug-releases/releases/download/v1.4.1/kpdbug_Linux_x86_64.tar.gz"
      sha256 "8a95820adac1aca5af73083a60f74930dab6fa9466b487773968633d2b971ae3"
      def install
        bin.install "kpdbug"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felipe-veas/k8s-pods-debug-releases/releases/download/v1.4.1/kpdbug_Linux_arm64.tar.gz"
      sha256 "a6638198140528e3403376d9b68b7cc752377cbf58950cd2ed8ab9e319a96f97"
      def install
        bin.install "kpdbug"
      end
    end
  end

  test do
    system "#{bin}/kpdbug --version"
  end
end
