# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kpdbug < Formula
  desc "Kubernetes pod debugging tool"
  homepage "https://github.com/felipe-veas/k8s-pods-debug"
  version "1.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felipe-veas/k8s-pods-debug/releases/download/v1.4.0/kpdbug_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "5a6d9483e01000ab3ee937df755026f0cdc1ddc52eb35d7a709b501e384303e5"

      def install
        bin.install "kpdbug"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felipe-veas/k8s-pods-debug/releases/download/v1.4.0/kpdbug_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2a6d22487b8c3c45ad9e3ba1e8ea7272e72dd1b10069f597de5ec6e95219723b"

      def install
        bin.install "kpdbug"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felipe-veas/k8s-pods-debug/releases/download/v1.4.0/kpdbug_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c51e4fb22130fae01b0810aa6b569dd99bbf3f6f53169038bcf6b368a3d0822e"
      def install
        bin.install "kpdbug"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felipe-veas/k8s-pods-debug/releases/download/v1.4.0/kpdbug_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "002afadba3d0ede446f02852ae4b77d5e64f6a3249e6e665352d7429c5d65ba3"
      def install
        bin.install "kpdbug"
      end
    end
  end

  test do
    system "#{bin}/kpdbug --version"
  end
end
